title: GraphHT
description: A Sampling-based Framework for Hypothesis Testing on Large Attributed Graphs
baseurl: "/GraphHT"
url: "https://carrieww.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Author information
author:
  name: Yun Wang
  email: carrie07@connect.hku.hk

# Social links
github_username: Carrieww

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 